language: node_js
node_js:
- '0.10'

addons:
  code_climate:
    repo_token:
      # CODECLIMATE_REPO_TOKEN
      secure: "NbqgqQfNBW4ovOrPD4nqLqs9D2JjUxZfJKvSwEdNQnLBPOpVJ7K4LE2owvACJBrfoEjQrXHbqLKjEcufLMI/9+qjqx/6ectJHez9nH5V+VOdgDX1VEV9RYC54OC8w7VLgEgT+PQY7001WvwTPl7p7H9NxWoQ0GknxrIiOgNt3J8="

before_install:
  - npm install -g npm

install:
  - npm install

script:
  - gulp lint test

after_success:
  - npm install -g codeclimate-test-reporter
  - gulp coverage
  - cat coverage/lcov.info | codeclimate
